#include"modified_shell.h"

/**
*mod_myexit-Exitstheshell.
*@info:TheStructurecontainingarguments.Usedtomaintainfunctionprototype.
*
*Return:Returnsanexitstatus;(0)ifinfo->argv[0]!="exit".
*/
intmod_myexit(modified_info_t*info)
{
intexitcheck;

if(info->argv[1])/*Ifthereisanexitargument*/
{
exitcheck=mod_erratoi(info->argv[1]);
if(exitcheck==-1)
{
info->status=2;
mod_print_error(info,"Illegalnumber:");
mod_eputs(info->argv[1]);
mod_eputchar('\n');
return(1);
}
info->err_num=mod_erratoi(info->argv[1]);
return(-2);
}
info->err_num=-1;
return(-2);
}

/**
*mod_mycd-Changesthecurrentdirectory.
*@info:Thestructcontainingpotentialarguments.Usedforprototype.
*
*Return:Always0.
*/
intmod_mycd(modified_info_t*info)
{
char*s,*dir,buffer[1024];
intchdir_ret;

s=mod_getcwd(buffer,1024);
if(!s)
mod_puts("TODO:>>getcwdfailureemsghere<<\n");
if(!info->argv[1])
{
dir=mod_getenv(info,"HOME=");
if(!dir)
chdir_ret=/*TODO:whatshouldthisbe?*/
mod_chdir((dir=mod_getenv(info,"PWD="))?dir:"/");
else
chdir_ret=mod_chdir(dir);
}
elseif(mod_strcmp(info->argv[1],"-")==0)
{
if(!mod_getenv(info,"OLDPWD="))
{
mod_puts(s);
mod_putchar('\n');
return(1);
}
mod_puts(mod_getenv(info,"OLDPWD=")),mod_putchar('\n');
chdir_ret=/*TODO:whatshouldthisbe?*/
mod_chdir((dir=mod_getenv(info,"OLDPWD="))?dir:"/");
}
else
chdir_ret=mod_chdir(info->argv[1]);
if(chdir_ret==-1)
{
mod_print_error(info,"can'tcdto");
mod_eputs(info->argv[1]);
mod_eputchar('\n');
}
else
{
mod_setenv(info,"OLDPWD",mod_getenv(info,"PWD="));
mod_setenv(info,"PWD",mod_getcwd(buffer,1024));
}
return(0);
}

/**
*mod_myhelp-Displayshelpinformation.
*@info:Structurecontainingpotentialarguments.Usedtomaintain
*constantfunctionprototype.
*
*Return:Always0.
*/
intmod_myhelp(modified_info_t*info)
{
char**arg_array;

arg_array=info->argv;
mod_puts("helpcallworks.Functionnotyetimplemented\n");
if(0)
mod_puts(*arg_array);/*tempatt_unusedworkaround*/
return(0);
}
