#include"modified_shell.h"

/**
*get_environment-returnsthestringarraycopyofourenvironment
*@info:Structurecontainingpotentialarguments.Usedtomaintain
*constantfunctionprototype.
*Return:Stringarraycontainingenvironmentvariables
*/
char**get_environment(modified_info_t*info)
{
if(!info->environment||info->env_changed)
{
info->environment=list_to_strings(info->env);
info->env_changed=0;
}

return(info->environment);
}

/**
*_unset_environment-Removeanenvironmentvariable
*@info:Structurecontainingpotentialarguments.Usedtomaintain
*constantfunctionprototype.
*@variable:thestringenvvariableproperty
*Return:1ondelete,0otherwise
*/
int_unset_environment(modified_info_t*info,char*variable)
{
list_t*node=info->env;
size_tindex=0;
char*p;

if(!node||!variable)
return(0);

while(node)
{
p=starts_with(node->str,variable);
if(p&&*p=='=')
{
info->env_changed=delete_node_at_index(&(info->env),index);
index=0;
node=info->env;
continue;
}
node=node->next;
index++;
}
return(info->env_changed);
}

/**
*_set_environment-Initializeanewenvironmentvariable,
*ormodifyanexistingone
*@info:Structurecontainingpotentialarguments.Usedtomaintain
*constantfunctionprototype.
*@variable:thestringenvvariableproperty
*@value:thestringenvvariablevalue
*Return:0onsuccess,1onfailure
*/
int_set_environment(modified_info_t*info,char*variable,char*value)
{
char*buffer=NULL;
list_t*node;
char*p;

if(!variable||!value)
return(0);

buffer=malloc(_str_len(variable)+_str_len(value)+2);
if(!buffer)
return(1);
_str_cpy(buffer,variable);
_str_cat(buffer,"=");
_str_cat(buffer,value);
node=info->env;
while(node)
{
p=starts_with(node->str,variable);
if(p&&*p=='=')
{
free(node->str);
node->str=buffer;
info->env_changed=1;
return(0);
}
node=node->next;
}
add_node_end(&(info->env),buffer,0);
free(buffer);
info->env_changed=1;
return(0);
}
