#include"shell.h"

/**
*initialize_info-initializesinfo_tstruct
*@info:structaddress
*/
voidinitialize_info(info_t*info)
{
info->arg=NULL;
info->argv=NULL;
info->path=NULL;
info->argc=0;
}

/**
*fill_info-initializesinfo_tstruct
*@info:structaddress
*@arguments:argumentvector
*/
voidfill_info(info_t*info,char**arguments)
{
inti=0;

info->filename=arguments[0];
if(info->arg)
{
info->argv=strtow(info->arg,"\t");
if(!info->argv)
{
info->argv=malloc(sizeof(char*)*2);
if(info->argv)
{
info->argv[0]=_strdup(info->arg);
info->argv[1]=NULL;
}
}
for(i=0;info->argv&&info->argv[i];i++)
;
info->argc=i;

replace_alias(info);
replace_vars(info);
}
}

/**
*free_info_struct-freesinfo_tstructfields
*@info:structaddress
*@free_all:trueiffreeingallfields
*/
voidfree_info_struct(info_t*info,intfree_all)
{
ffree(info->argv);
info->argv=NULL;
info->path=NULL;
if(free_all)
{
if(!info->cmd_buf)
free(info->arg);
if(info->env)
free_list(&(info->env));
if(info->history)
free_list(&(info->history));
if(info->alias)
free_list(&(info->alias));
ffree(info->environ);
info->environ=NULL;
bfree((void**)info->cmd_buf);
if(info->readfd>2)
close(info->readfd);
_putchar(BUF_FLUSH);
}
}
