#include"shell.h"

/**
*get_history_file_path-getsthehistoryfilepath
*@info:parameterstruct
*
*Return:allocatedstringcontaininghistoryfilepath
*/
char*get_history_file_path(info_t*info)
{
char*buf,*dir;

dir=_getenv(info,"HOME=");
if(!dir)
return(NULL);
buf=malloc(sizeof(char)*(_strlen(dir)+_strlen(HISTORY_FILE)+2));
if(!buf)
return(NULL);
buf[0]=0;
_strcpy(buf,dir);
_strcat(buf,"/");
_strcat(buf,HISTORY_FILE);
return(buf);
}

/**
*write_history_to_file-createsafile,orappendstoanexistingfile
*@info:theparameterstruct
*
*Return:1onsuccess,else-1
*/
intwrite_history_to_file(info_t*info)
{
ssize_tfd;
char*filename=get_history_file_path(info);
list_t*node=NULL;

if(!filename)
return(-1);

fd=open(filename,O_CREAT|O_TRUNC|O_RDWR,0644);
free(filename);
if(fd==-1)
return(-1);
for(node=info->history;node;node=node->next)
{
_putsfd(node->str,fd);
_putfd('\n',fd);
}
_putfd(BUF_FLUSH,fd);
close(fd);
return(1);
}

/**
*read_history_from_file-readshistoryfromfile
*@info:theparameterstruct
*
*Return:histcountonsuccess,0otherwise
*/
intread_history_from_file(info_t*info)
{
inti,last=0,linecount=0;
ssize_tfd,rdlen,fsize=0;
structstatst;
char*buf=NULL,*filename=get_history_file_path(info);

if(!filename)
return(0);

fd=open(filename,O_RDONLY);
free(filename);
if(fd==-1)
return(0);
if(!fstat(fd,&st))
fsize=st.st_size;
if(fsize<2)
return(0);
buf=malloc(sizeof(char)*(fsize+1));
if(!buf)
return(0);
rdlen=read(fd,buf,fsize);
buf[fsize]=0;
if(rdlen<=0)
return(free(buf),0);
close(fd);
for(i=0;i<fsize;i++)
if(buf[i]=='\n')
{
buf[i]=0;
build_history_list(info,buf+last,linecount++);
last=i+1;
}
if(last!=i)
build_history_list(info,buf+last,linecount++);
free(buf);
info->histcount=linecount;
while(info->histcount-->=HISTORY_MAX)
delete_node_at_index(&(info->history),0);
renumber_history(info);
return(info->histcount);
}

/**
*add_history_entry-addsentrytoahistorylinkedlist
*@info:parameterstruct
*@buf:buffer
*@linecount:thehistorylinecount,histcount
*
*Return:Always0
*/
intadd_history_entry(info_t*info,char*buf,intlinecount)
{
list_t*node=NULL;

if(info->history)
node=info->history;
add_node_end(&node,buf,linecount);

if(!info->history)
info->history=node;
return(0);
}

/**
*renumber_history_list-renumbersthehistorylinkedlistafterchanges
*@info:parameterstruct
*
*Return:thenewhistcount
*/
intrenumber_history_list(info_t*info)
{
list_t*node=info->history;
inti=0;

while(node)
{
node->num=i++;
node=node->next;
}
return(info->histcount=i);
}
