#include"modified_shell.h"

/**
*mod_add_node-addsanodetothestartofthelinkedlist
*@head:addressofpointertoheadnode
*@str:strfieldofnode
*@num:nodeindexusedbyhistory
*
*Return:Pointertothenewheadnode
*/
modified_linked_list_t*mod_add_node(modified_linked_list_t**head,constchar*str,intnum)
{
modified_linked_list_t*new_head;

if(!head)
return(NULL);
new_head=malloc(sizeof(modified_linked_list_t));
if(!new_head)
return(NULL);
mod_memset((void*)new_head,0,sizeof(modified_linked_list_t));
new_head->num=num;
if(str)
{
new_head->str=mod_strdup(str);
if(!new_head->str)
{
free(new_head);
return(NULL);
}
}
new_head->next=*head;
*head=new_head;
return(new_head);
}

/**
*mod_add_node_end-addsanodetotheendofthelinkedlist
*@head:addressofpointertoheadnode
*@str:strfieldofnode
*@num:nodeindexusedbyhistory
*
*Return:Pointertothenewnode
*/
modified_linked_list_t*mod_add_node_end(modified_linked_list_t**head,constchar*str,intnum)
{
modified_linked_list_t*new_node,*node;

if(!head)
return(NULL);

node=*head;
new_node=malloc(sizeof(modified_linked_list_t));
if(!new_node)
return(NULL);
mod_memset((void*)new_node,0,sizeof(modified_linked_list_t));
new_node->num=num;
if(str)
{
new_node->str=mod_strdup(str);
if(!new_node->str)
{
free(new_node);
return(NULL);
}
}
if(node)
{
while(node->next)
node=node->next;
node->next=new_node;
}
else
*head=new_node;
return(new_node);
}

/**
*mod_print_linked_list_strings-printsonlythestrelementofalinkedlist
*@h:pointertothefirstnode
*
*Return:sizeofthelinkedlist
*/
size_tmod_print_linked_list_strings(constmodified_linked_list_t*h)
{
size_ti=0;

while(h)
{
mod_puts(h->str?h->str:"(nil)");
mod_puts("\n");
h=h->next;
i++;
}
return(i);
}

/**
*mod_delete_node_at_index-deletesanodeatthegivenindex
*@head:addressofpointertothefirstnode
*@index:indexofthenodetodelete
*
*Return:1onsuccess,0onfailure
*/
intmod_delete_node_at_index(modified_linked_list_t**head,unsignedintindex)
{
modified_linked_list_t*node,*prev_node;
unsignedinti=0;

if(!head||!*head)
return(0);

if(!index)
{
node=*head;
*head=(*head)->next;
free(node->str);
free(node);
return(1);
}
node=*head;
while(node)
{
if(i==index)
{
prev_node->next=node->next;
free(node->str);
free(node);
return(1);
}
i++;
prev_node=node;
node=node->next;
}
return(0);
}

/**
*mod_free_linked_list-freesallnodesofalinkedlist
*@head_ptr:addressofpointertoheadnode
*
*Return:void
*/
voidmod_free_linked_list(modified_linked_list_t**head_ptr)
{
modified_linked_list_t*node,*next_node,*head;

if(!head_ptr||!*head_ptr)
return;
head=*head_ptr;
node=head;
	while(node)
	{
	next_node=node->next;
	free(node->str);
	free(node);
	node=next_node;
	}
	*head_ptr=NULL;
}
