#include"shell.h"

/**
*is_executable-determinesifafileisanexecutablecommand
*@path:pathtothefile
*
*Return:1iftrue,0otherwise
*/
intis_executable(char*path)
{
structstatst;

if(!path||stat(path,&st))
return0;

if(st.st_mode&S_IFREG&&st.st_mode&S_IXUSR)
{
return1;
}
return0;
}

/**
*duplicate_chars-duplicatescharacters
*@source:thesourcestring
*@start:startingindex
*@stop:stoppingindex
*
*Return:pointertonewbuffer
*/
char*duplicate_chars(constchar*source,intstart,intstop)
{
staticcharbuffer[1024];
inti=0,k=0;

for(k=0,i=start;i<stop;i++)
if(source[i]!=':')
buffer[k++]=source[i];
buffer[k]='\0';
returnbuffer;
}

/**
*find_executable_path-findsthefullpathofanexecutablecommand
*@pathstr:thePATHstring
*@cmd:thecommandtofind
*
*Return:fullpathofcmdiffound,orNULL
*/
char*find_executable_path(constchar*pathstr,constchar*cmd)
{
inti=0,curr_pos=0;
char*path;

if(!pathstr)
returnNULL;
if((_strlen(cmd)>2)&&starts_with(cmd,"./"))
{
if(is_executable(cmd))
return_strdup(cmd);
}
while(1)
{
if(!pathstr[i]||pathstr[i]==':')
{
path=duplicate_chars(pathstr,curr_pos,i);
if(!*path)
_strcat(path,cmd);
else
{
_strcat(path,"/");
_strcat(path,cmd);
}
if(is_executable(path))
returnpath;
if(!pathstr[i])
break;
curr_pos=i+1;
}
i++;
}
returnNULL;
}
