#include"shell.h"

/**
*shell_loop-mainshellloop
*@info:theparameter&returninfostruct
*@av:theargumentvectorfrommain()
*
*Return:0onsuccess,1onerror,orerrorcode
*/
intshell_loop(info_t*info,char**av)
{
	ssize_tr=0;
	intbuiltin_ret=0;

	while(r!=-1&&builtin_ret!=-2)
	{
		clear_info(info);
		if(is_interactive(info))
			print_prompt(info);
		r=get_input(info);
		if(r!=-1)
		{
			set_info(info,av);
			builtin_ret=find_builtin(info);
			if(builtin_ret==-1)
				find_command(info);
		}
		elseif(is_interactive(info))
			_putchar('\n');
		free_info(info,0);
	}
	write_history(info);
	free_info(info,1);
	if(!is_interactive(info)&&info->status)
		exit(info->status);
	if(builtin_ret==-2)
	{
		if(info->error_num==-1)
			exit(info->status);
		exit(info->error_num);
	}
	return(builtin_ret);
}

/**
*find_builtin-findsabuiltincommand
*@info:theparameter&returninfostruct
*
*Return:-1ifbuiltinnotfound,
*0ifbuiltinexecutedsuccessfully,
*1ifbuiltinfoundbutnotsuccessful,
*-2ifbuiltinsignalsexit()
*/
intfind_builtin(info_t*info)
{
	inti,builtin_ret=-1;
	builtin_tablebuiltintbl[]={
		{"exit",my_exit},
		{"env",my_env},
		{"help",my_help},
		{"history",my_history},
		{"setenv",my_setenv},
		{"unsetenv",my_unsetenv},
		{"cd",my_cd},
		{"alias",my_alias},
		{NULL,NULL}
	};

	for(i=0;builtintbl[i].type;i++)
	{
		if(_strcmp(info->argv[0],builtintbl[i].type)==0)
		{
			info->line_count++;
			builtin_ret=builtintbl[i].func(info);
			break;
		}
	}
	return(builtin_ret);
}

/**
*find_command-findsacommandinPATH
*@info:theparameter&returninfostruct
*
*Return:void
*/
voidfind_command(info_t*info)
{
	char*path=NULL;

	info->path=info->argv[0];
	if(info->line_count_flag==1)
	{
		info->line_count++;
		info->line_count_flag=0;
	}
	if(should_execute_command(info->arg))
	{
		path=find_path(info,get_environment_variable(info,"PATH="),info->argv[0]);
		if(path)
		{
			info->path=path;
			fork_command(info);
		}
		else
		{
			if((is_interactive(info)||get_environment_variable(info,"PATH=")
				||info->argv[0][0]=='/')&&is_cmd(info,info->argv[0]))
				fork_command(info);
			elseif(*(info->arg)!='\n')
			{
				info->status=127;
				print_error(info,"notfound\n");
			}
		}
	}
}

/**
*fork_command-forksanexecthreadtoruncmd
*@info:theparameter&returninfostruct
*
*Return:void
*/
voidfork_command(info_t*info)
{
	pid_tchild_pid;

	child_pid=fork();
	if(child_pid==-1)
	{
		perror("Error:");
		return;
	}
	if(child_pid==0)
	{
		if(execve(info->path,info->argv,get_environ(info))==-1)
		{
			free_info(info,1);
			if(errno==EACCES)
				exit(126);
			exit(1);
		}
	}
	else
	{
		wait(&(info->status));
		if(WIFEXITED(info->status))
		{
			info->status=WEXITSTATUS(info->status);
			if(info->status==126)
				print_error(info,"Permissiondenied\n");
		}
	}
}
